/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.SessionUser;
import Persistencia.Entities.Usuario;
import Persistencia.Implementacion.ImplPerfil;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebas
 */
public class Perfil extends javax.swing.JFrame {

    private ImplPerfil implPerfil;
    private Ventanas.Usuarios usuarios;

    /**
     * Creates new form Perfil
     */
    public Perfil(Ventanas.Usuarios usuarios) {
        implPerfil = new ImplPerfil();
        this.usuarios = usuarios;
        initComponents();
        initElement();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPerfil = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar_Perfil = new javax.swing.JButton();
        btnCancelar_Perfil = new javax.swing.JButton();
        btnOpcion_Perfil = new javax.swing.JButton();
        txtDescripcion_Perfil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo_Perfil = new javax.swing.JTextField();
        panelGrid_Perfil = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGrid_Perfil = new javax.swing.JTable();
        txtBuscar_Codigo_Perfil = new javax.swing.JTextField();
        txtBuscar_Descripcion_Perfil = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnBuscar_Todos = new javax.swing.JButton();

        setTitle("Perfil");

        panelPerfil.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("Descripción");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnGuardar_Perfil.setText("Guardar");
        btnGuardar_Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar_PerfilActionPerformed(evt);
            }
        });

        btnCancelar_Perfil.setText("Cancelar");
        btnCancelar_Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_PerfilActionPerformed(evt);
            }
        });

        btnOpcion_Perfil.setText("Nuevo");
        btnOpcion_Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion_PerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnGuardar_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnOpcion_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnCancelar_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar_Perfil, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnOpcion_Perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setText("Código");

        txtCodigo_Perfil.setEnabled(false);

        javax.swing.GroupLayout panelPerfilLayout = new javax.swing.GroupLayout(panelPerfil);
        panelPerfil.setLayout(panelPerfilLayout);
        panelPerfilLayout.setHorizontalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPerfilLayout.createSequentialGroup()
                        .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addGap(96, 96, 96)
                        .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodigo_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcion_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPerfilLayout.setVerticalGroup(
            panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tableGrid_Perfil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(tableGrid_Perfil);

        jLabel3.setText("Id");

        jLabel4.setText("Descripción");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscar_Todos.setText("Todos");
        btnBuscar_Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_TodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGrid_PerfilLayout = new javax.swing.GroupLayout(panelGrid_Perfil);
        panelGrid_Perfil.setLayout(panelGrid_PerfilLayout);
        panelGrid_PerfilLayout.setHorizontalGroup(
            panelGrid_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrid_PerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGrid_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGrid_PerfilLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelGrid_PerfilLayout.createSequentialGroup()
                        .addGroup(panelGrid_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtBuscar_Codigo_Perfil))
                        .addGap(47, 47, 47)
                        .addGroup(panelGrid_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscar_Descripcion_Perfil)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelGrid_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBuscar_Todos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        panelGrid_PerfilLayout.setVerticalGroup(
            panelGrid_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrid_PerfilLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(panelGrid_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelGrid_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGrid_PerfilLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelGrid_PerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar_Codigo_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar_Descripcion_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panelGrid_PerfilLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar_Todos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGrid_Perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(panelPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelGrid_Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelar_PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_PerfilActionPerformed
        limpiarCampos();
        btnPorDefecto();
    }//GEN-LAST:event_btnCancelar_PerfilActionPerformed

    private void btnGuardar_PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar_PerfilActionPerformed
        String g = btnGuardar_Perfil.getText();
        switch (g) {
            case "Guardar":
                this.guardar();
                break;
            case "Guardar Cambios":
                this.editar();
                break;
        }
        btnPorDefecto();
        limpiarCampos();
    }//GEN-LAST:event_btnGuardar_PerfilActionPerformed

    private void btnOpcion_PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion_PerfilActionPerformed
        String g = btnOpcion_Perfil.getText();
        switch (g) {
            case "Eliminar":
                this.eliminar();
                break;
        }
        btnPorDefecto();
        limpiarCampos();
    }//GEN-LAST:event_btnOpcion_PerfilActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        findAll(implPerfil.buscar(txtBuscar_Codigo_Perfil.getText(), txtBuscar_Descripcion_Perfil.getText()));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscar_TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar_TodosActionPerformed
        findAllEntities();
        txtBuscar_Codigo_Perfil.setText("");
        txtBuscar_Descripcion_Perfil.setText("");
    }//GEN-LAST:event_btnBuscar_TodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar_Todos;
    private javax.swing.JButton btnCancelar_Perfil;
    private javax.swing.JButton btnGuardar_Perfil;
    private javax.swing.JButton btnOpcion_Perfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGrid_Perfil;
    private javax.swing.JPanel panelPerfil;
    private javax.swing.JTable tableGrid_Perfil;
    private javax.swing.JTextField txtBuscar_Codigo_Perfil;
    private javax.swing.JTextField txtBuscar_Descripcion_Perfil;
    private javax.swing.JTextField txtCodigo_Perfil;
    private javax.swing.JTextField txtDescripcion_Perfil;
    // End of variables declaration//GEN-END:variables

    public void cargarDatoGrid(String codigo) {
        String descripcion = txtDescripcion_Perfil.getText();
        addRow(codigo, descripcion);
    }

    public void addRow(String codigo, String descripcion) {
        DefaultTableModel model = (DefaultTableModel) tableGrid_Perfil.getModel();
        model.addRow(new Object[]{codigo, descripcion});
    }

    private void limpiarCampos() {
        txtDescripcion_Perfil.setText("");
        txtCodigo_Perfil.setText("");
    }

    private void initElement() {
        findAllEntities();
        tableGrid_Perfil.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = tableGrid_Perfil.rowAtPoint(e.getPoint());
                int columna = tableGrid_Perfil.columnAtPoint(e.getPoint());
                if ((fila > -1) && (columna > -1)) {
                    txtCodigo_Perfil.setText(getRowVector(fila)[0]);
                    txtDescripcion_Perfil.setText(getRowVector(fila)[1]);
                    btnGuardar_Perfil.setText("Guardar Cambios");
                    btnOpcion_Perfil.setText("Eliminar");
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }

    public String[] getRowVector(int fila) {
        DefaultTableModel model = (DefaultTableModel) tableGrid_Perfil.getModel();
        int col = tableGrid_Perfil.getColumnCount();
        String result = "";
        for (int i = 0; i < col; i++) {
            result += (i == 0 ? "" : " - ") + model.getValueAt(fila, i).toString();
        }
        return result.split("-");
    }

    private void btnPorDefecto() {
        btnGuardar_Perfil.setText("Guardar");
        btnOpcion_Perfil.setText("Nuevo");
    }

    public void guardar() {
        try {
            Boolean validar = true;
            if (txtDescripcion_Perfil.getText().equals("")) {
                validar = false;
            }
            if (validar) {
                Persistencia.Entities.Perfil perfil = new Persistencia.Entities.Perfil();
                perfil.setDescripcion(txtDescripcion_Perfil.getText());
                if (implPerfil.createPerfil(perfil) != null) {
                    JOptionPane.showMessageDialog(this, "Perfil creado");
                    cargarDatoGrid(perfil.getIdperfil().toString());
                    reloadSelectPerfil();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al crear el Perfil");
                }
            }

            //3470
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    private void editar() {
        try {
            Boolean validar = true;
            if (txtDescripcion_Perfil.getText().equals("")) {
                validar = false;
            }
            if (validar) {
                Persistencia.Entities.Perfil perfil = implPerfil.findPerfilById(Integer.parseInt(txtCodigo_Perfil.getText().trim()));
                perfil.setDescripcion(txtDescripcion_Perfil.getText());
                if (implPerfil.editPerfil(perfil) != null) {
                    JOptionPane.showMessageDialog(this, "Perfil Editado");
                    clear_Table();
                    findAllEntities();
                    reloadSelectPerfil();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al Editar el Perfil");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    private void eliminar() {
        try {
            Persistencia.Entities.Perfil perfil = implPerfil.findPerfilById(Integer.parseInt(txtCodigo_Perfil.getText().trim()));
            Boolean validar = true;
            String mensaje = "";
            if (txtCodigo_Perfil.getText().equals("")) {
                validar = false;
            }
            if (perfil.getPermisosList().size() != 0) {
                mensaje += "Hay Permisos con este Perfil \n";
                validar = false;
            }
            if (perfil.getUsuarioList().size() != 0) {
                mensaje += "Hay Usuarios con este Perfil \n";
                validar = false;
            }
            if (validar) {

                if (implPerfil.elimiarPerfil(perfil) == null) {
                    JOptionPane.showMessageDialog(this, "Perfil Eliminado");
                    clear_Table();
                    findAllEntities();
                    reloadSelectPerfil();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al Elimimnar el Perfil");
                }
            }else {
                JOptionPane.showMessageDialog(this, mensaje);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    private void clear_Table() {
        DefaultTableModel modelo = (DefaultTableModel) tableGrid_Perfil.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    private void findAllEntities() {
        clear_Table();
        List<Persistencia.Entities.Perfil> list = implPerfil.findPerfilEntities();
        for (int i = 0; i < list.size(); i++) {
            addRow(list.get(i).getIdperfil().toString(), list.get(i).getDescripcion());
        }
    }

    private void findAll(List<Persistencia.Entities.Perfil> list) {
        clear_Table();
        for (int i = 0; i < list.size(); i++) {
            addRow(list.get(i).getIdperfil().toString(),
                    list.get(i).getDescripcion().toString());
        }
    }

    public void reloadSelectPerfil() {
        if (this.usuarios != null) {
            this.usuarios.initPerfil();
        }
    }

    private boolean isValidarSession() {
        Usuario usuario = SessionUser.getUsuario();
        Boolean res = false;
        if (usuario != null) {
            List<Persistencia.Entities.Permisos> listP = usuario.getIdperfil().getPermisosList();
            for (int i = 0; i < listP.size(); i++) {
                if (listP.get(i).getIdPermisos() == SessionUser.isPerfil) {
                    res = true;
                }
            }
        }
        return res;
    }
}
