/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.SessionUser;
import Persistencia.Entities.Usuario;
import Persistencia.Implementacion.ImplTipo_documento;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebas
 */
public class Tipo_Documento extends javax.swing.JFrame {

    private ImplTipo_documento implTipo_documento = null;
    private Ventanas.Usuarios usuarios;

    /**
     * Creates new form Tipo_Documento
     */
    public Tipo_Documento(Ventanas.Usuarios usuarios) {
        implTipo_documento = new ImplTipo_documento();
        this.usuarios = usuarios;
        initComponents();
        initElement();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTipo_Documento = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnGuardar_Tipo_Documento = new javax.swing.JButton();
        btnOpcion_Tipo_Documento = new javax.swing.JButton();
        btnCancelar_Tipo_Documento = new javax.swing.JButton();
        txtDescripcion_Tipo_Documento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo_Tipo_Documento = new javax.swing.JTextField();
        panelGrid_Tipo_Documento = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGrid_Tipo_Documento = new javax.swing.JTable();
        txtBuscar_Codigo_Tipo_Documento = new javax.swing.JTextField();
        txtBuscar_Descripcion_Tipo_Documento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Tipo de Documento");

        panelTipo_Documento.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setText("Descripción");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btnGuardar_Tipo_Documento.setText("Guardar");
        btnGuardar_Tipo_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar_Tipo_DocumentoActionPerformed(evt);
            }
        });

        btnOpcion_Tipo_Documento.setText("Nuevo");
        btnOpcion_Tipo_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion_Tipo_DocumentoActionPerformed(evt);
            }
        });

        btnCancelar_Tipo_Documento.setText("Cancelar");
        btnCancelar_Tipo_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar_Tipo_DocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnOpcion_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnCancelar_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnGuardar_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpcion_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel1.setText("Código");

        txtCodigo_Tipo_Documento.setEnabled(false);
        txtCodigo_Tipo_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigo_Tipo_DocumentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTipo_DocumentoLayout = new javax.swing.GroupLayout(panelTipo_Documento);
        panelTipo_Documento.setLayout(panelTipo_DocumentoLayout);
        panelTipo_DocumentoLayout.setHorizontalGroup(
            panelTipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipo_DocumentoLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(panelTipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelTipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescripcion_Tipo_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtCodigo_Tipo_Documento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTipo_DocumentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        panelTipo_DocumentoLayout.setVerticalGroup(
            panelTipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTipo_DocumentoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelTipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTipo_DocumentoLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtCodigo_Tipo_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescripcion_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        tableGrid_Tipo_Documento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descripción"
            }
        ));
        jScrollPane1.setViewportView(tableGrid_Tipo_Documento);

        jLabel3.setText("Id");

        jLabel4.setText("Descripción");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Todos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGrid_Tipo_DocumentoLayout = new javax.swing.GroupLayout(panelGrid_Tipo_Documento);
        panelGrid_Tipo_Documento.setLayout(panelGrid_Tipo_DocumentoLayout);
        panelGrid_Tipo_DocumentoLayout.setHorizontalGroup(
            panelGrid_Tipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrid_Tipo_DocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGrid_Tipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addGroup(panelGrid_Tipo_DocumentoLayout.createSequentialGroup()
                        .addGroup(panelGrid_Tipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscar_Codigo_Tipo_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(76, 76, 76)
                        .addGroup(panelGrid_Tipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscar_Descripcion_Tipo_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelGrid_Tipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelGrid_Tipo_DocumentoLayout.setVerticalGroup(
            panelGrid_Tipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGrid_Tipo_DocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGrid_Tipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGroup(panelGrid_Tipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGrid_Tipo_DocumentoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelGrid_Tipo_DocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar_Codigo_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar_Descripcion_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(panelGrid_Tipo_DocumentoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGrid_Tipo_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTipo_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(panelTipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelGrid_Tipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar_Tipo_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar_Tipo_DocumentoActionPerformed
        String g = btnGuardar_Tipo_Documento.getText();
        switch (g) {
            case "Guardar":
                this.guardar();
                break;
            case "Guardar Cambios":
                this.editar();
                break;
        }
        btnPorDefecto();
        limpiarCampos();
    }//GEN-LAST:event_btnGuardar_Tipo_DocumentoActionPerformed

    private void btnCancelar_Tipo_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar_Tipo_DocumentoActionPerformed
        limpiarCampos();
        btnPorDefecto();
    }//GEN-LAST:event_btnCancelar_Tipo_DocumentoActionPerformed

    private void txtCodigo_Tipo_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigo_Tipo_DocumentoActionPerformed

    }//GEN-LAST:event_txtCodigo_Tipo_DocumentoActionPerformed

    private void btnOpcion_Tipo_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion_Tipo_DocumentoActionPerformed
        String g = btnOpcion_Tipo_Documento.getText();
        switch (g) {
            case "Eliminar":
                this.eliminar();
                break;
        }
        btnPorDefecto();
        limpiarCampos();
    }//GEN-LAST:event_btnOpcion_Tipo_DocumentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        findAll(implTipo_documento.buscar(txtBuscar_Codigo_Tipo_Documento.getText(), txtBuscar_Descripcion_Tipo_Documento.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        findAllEntities();
        txtBuscar_Codigo_Tipo_Documento.setText("");
        txtBuscar_Descripcion_Tipo_Documento.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tipo_Documento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tipo_Documento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tipo_Documento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tipo_Documento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tipo_Documento(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar_Tipo_Documento;
    private javax.swing.JButton btnGuardar_Tipo_Documento;
    private javax.swing.JButton btnOpcion_Tipo_Documento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGrid_Tipo_Documento;
    private javax.swing.JPanel panelTipo_Documento;
    private javax.swing.JTable tableGrid_Tipo_Documento;
    private javax.swing.JTextField txtBuscar_Codigo_Tipo_Documento;
    private javax.swing.JTextField txtBuscar_Descripcion_Tipo_Documento;
    private javax.swing.JTextField txtCodigo_Tipo_Documento;
    private javax.swing.JTextField txtDescripcion_Tipo_Documento;
    // End of variables declaration//GEN-END:variables

    public void cargarDatoGrid(String codigo) {
        String descripcion = txtDescripcion_Tipo_Documento.getText();
        addRow(codigo, descripcion);
    }

    public void addRow(String codigo, String descripcion) {
        DefaultTableModel model = (DefaultTableModel) tableGrid_Tipo_Documento.getModel();
        model.addRow(new Object[]{codigo, descripcion});
    }

    private void limpiarCampos() {
        txtDescripcion_Tipo_Documento.setText("");
        txtCodigo_Tipo_Documento.setText("");
    }

    private void initElement() {
        findAllEntities();
        tableGrid_Tipo_Documento.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = tableGrid_Tipo_Documento.rowAtPoint(e.getPoint());
                int columna = tableGrid_Tipo_Documento.columnAtPoint(e.getPoint());
                if ((fila > -1) && (columna > -1)) {
                    txtCodigo_Tipo_Documento.setText(getRowVector(fila)[0]);
                    txtDescripcion_Tipo_Documento.setText(getRowVector(fila)[1]);
                    btnGuardar_Tipo_Documento.setText("Guardar Cambios");
                    btnOpcion_Tipo_Documento.setText("Eliminar");
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }

        });
    }

    public String[] getRowVector(int fila) {
        DefaultTableModel model = (DefaultTableModel) tableGrid_Tipo_Documento.getModel();
        int col = tableGrid_Tipo_Documento.getColumnCount();
        String result = "";
        for (int i = 0; i < col; i++) {
            result += (i == 0 ? "" : " - ") + model.getValueAt(fila, i).toString();
        }
        return result.split("-");
    }

    private void btnPorDefecto() {
        btnGuardar_Tipo_Documento.setText("Guardar");
        btnOpcion_Tipo_Documento.setText("Nuevo");
    }

    public void guardar() {
        try {
            Boolean validar = true;
            if (txtDescripcion_Tipo_Documento.getText().equals("")) {
                validar = false;
            }
            if (validar) {
                Persistencia.Entities.TipoDocumento tipo_Documento = new Persistencia.Entities.TipoDocumento();
                tipo_Documento.setDescripcion(txtDescripcion_Tipo_Documento.getText());
                if (implTipo_documento.createTipoDocumento(tipo_Documento) != null) {
                    JOptionPane.showMessageDialog(this, "Tipo de Documento creado");
                    cargarDatoGrid(tipo_Documento.getIdTipodocumento().toString());
                    reloadSelectTipoDocumento();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al crear el Tipo de Documento");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    public void editar() {
        try {
            Boolean validar = true;

            if (txtDescripcion_Tipo_Documento.getText().equals("")) {
                validar = false;
            }
            if (validar) {
                Persistencia.Entities.TipoDocumento tipo_Documento = implTipo_documento.findTipoDocumentoById(Integer.parseInt(txtCodigo_Tipo_Documento.getText().trim()));
                tipo_Documento.setDescripcion(txtDescripcion_Tipo_Documento.getText());
                if (implTipo_documento.editarTipoDocumento(tipo_Documento) != null) {
                    JOptionPane.showMessageDialog(this, "Tipo de Documento Editado");
                    clear_Table();
                    findAllEntities();
                    reloadSelectTipoDocumento();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al Editar el Tipo de Documento");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    private void findAllEntities() {
        clear_Table();
        List<Persistencia.Entities.TipoDocumento> list = implTipo_documento.findTipoDocumentoEntities();
        for (int i = 0; i < list.size(); i++) {
            addRow(list.get(i).getIdTipodocumento().toString(), list.get(i).getDescripcion());
        }
    }

    private void findAll(List<Persistencia.Entities.TipoDocumento> list) {
        clear_Table();
        for (int i = 0; i < list.size(); i++) {
            addRow(list.get(i).getIdTipodocumento().toString(),
                    list.get(i).getDescripcion().toString());
        }
    }

    private void clear_Table() {
        DefaultTableModel modelo = (DefaultTableModel) tableGrid_Tipo_Documento.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    private void eliminar() {
        try {
            Persistencia.Entities.TipoDocumento tipo_Documento = implTipo_documento.findTipoDocumentoById(Integer.parseInt(txtCodigo_Tipo_Documento.getText().trim()));
            Boolean validar = true;
            String mensaje = "";
            if (txtCodigo_Tipo_Documento.getText().equals("")) {
                validar = false;
            }
            if (tipo_Documento.getUsuarioList().size() != 0) {
                mensaje += "Hay usuarios con éste tipo de documento \n";
                validar = false;
            }
            if (tipo_Documento.getClienteList().size() != 0) {
                mensaje += "Hay cientes con éste tipo de documento";
                validar = false;
            }
            if (validar) {
                if (implTipo_documento.elimiarTipoDocumento(tipo_Documento) == null) {
                    JOptionPane.showMessageDialog(this, "Tipo de Documento Eliminado");
                    clear_Table();
                    findAllEntities();
                    reloadSelectTipoDocumento();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al Eliminar el Tipo de Documento");
                }
            } else {
                JOptionPane.showMessageDialog(this, mensaje);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    public void reloadSelectTipoDocumento() {
        if (this.usuarios != null) {
            this.usuarios.initTipoDocumento();
        }
    }

    private boolean isValidarSession() {
        Usuario usuario = SessionUser.getUsuario();
        Boolean res = true;
        if (usuario != null) {
            List<Persistencia.Entities.Permisos> listP = usuario.getIdperfil().getPermisosList();
            for (int i = 0; i < listP.size(); i++) {
                if (listP.get(i).getIdPermisos() == SessionUser.isTipodocumento) {
                    res = true;
                }
            }
        }
        return res;
    }
}
