/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.ComboItem;
import Clases.SessionUser;
import Persistencia.Entities.Estado;
import Persistencia.Entities.Perfil;
import Persistencia.Entities.TipoDocumento;
import Persistencia.Entities.Usuario;
import Persistencia.Implementacion.ImplEstado;
import Persistencia.Implementacion.ImplPerfil;
import Persistencia.Implementacion.ImplTipo_documento;
import Persistencia.Implementacion.ImplUsuario;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yuri
 */
public class Usuarios extends javax.swing.JFrame {

    private ImplTipo_documento implTipo_documento = null;
    private ImplPerfil implPerfil = null;
    private ImplUsuario implUsuario = null;
    private ImplEstado implEstado = null;

    /**
     * Creates new form Usuarios
     */
    public Usuarios() {
        implTipo_documento = new ImplTipo_documento();
        implPerfil = new ImplPerfil();
        implUsuario = new ImplUsuario();
        implEstado = new ImplEstado();
        initComponents();
        initElement();
        initData();
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        AvancePhilaePUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("AvancePhilaePU").createEntityManager();
        usuarioQuery = java.beans.Beans.isDesignTime() ? null : AvancePhilaePUEntityManager.createQuery("SELECT u FROM Usuario u");
        usuarioList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : usuarioQuery.getResultList();
        panel_Usuario = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbxTipoDocumento = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtNumero_Documento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelefono_Movil = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCorreo_Electronico = new javax.swing.JTextField();
        cbxEstado = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtNombres_Completos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrimer_Apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSegundo_Apellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtNombre_Usuario = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbxPerfil = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        JLabel14 = new javax.swing.JLabel();
        txtClave = new javax.swing.JPasswordField();
        txtConfirmar_Clave = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnOpcion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnMostrar_Form = new javax.swing.JButton();
        panelGrid = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGrid = new javax.swing.JTable();
        txtBuscar_Identificacion = new javax.swing.JTextField();
        txtBuscar_Nombre = new javax.swing.JTextField();
        txtBuscar_numeroDocumento = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBuscar_Todos = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnTipo_Documento = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        btnPermisos = new javax.swing.JButton();

        setTitle("Usuarios");

        panel_Usuario.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("*Tipo documento ");

        cbxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        jLabel3.setText("*Numero  documento");

        txtNumero_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumero_DocumentoActionPerformed(evt);
            }
        });

        jLabel9.setText("Teléfono Móvil");

        jLabel14.setText("Correo  Electrónico");

        jLabel11.setText("*Estado");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));

        jLabel4.setText("*Nombres completos");

        txtNombres_Completos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombres_CompletosActionPerformed(evt);
            }
        });

        jLabel5.setText("*Primer apellido");

        txtPrimer_Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimer_ApellidoActionPerformed(evt);
            }
        });

        jLabel6.setText("Segundo apellido");

        jLabel7.setText("*Teléfono1");

        txtTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefono1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Teléfono2");

        txtTelefono2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefono2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel12.setText("*Nombre Usuario");

        txtNombre_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_UsuarioActionPerformed(evt);
            }
        });

        jLabel13.setText("*Contraseña");

        jLabel16.setText("*Perfil");

        cbxPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        cbxPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPerfilActionPerformed(evt);
            }
        });

        jLabel17.setText("Datos de Ingreso");

        JLabel14.setText("*Confirmar Contraseña");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(JLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClave)
                            .addComponent(txtConfirmar_Clave, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel13)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmar_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbxPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnOpcion.setText("Nuevo");
        btnOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcionActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btnOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel10.setText("FORMULARIO");

        jLabel1.setText("Código");

        txtCodigo.setEnabled(false);

        javax.swing.GroupLayout panel_UsuarioLayout = new javax.swing.GroupLayout(panel_Usuario);
        panel_Usuario.setLayout(panel_UsuarioLayout);
        panel_UsuarioLayout.setHorizontalGroup(
            panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_UsuarioLayout.createSequentialGroup()
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombres_Completos, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrimer_Apellido, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSegundo_Apellido)
                            .addComponent(txtNumero_Documento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_UsuarioLayout.createSequentialGroup()
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(42, 42, 42)
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefono2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtTelefono1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_UsuarioLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_UsuarioLayout.createSequentialGroup()
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addGap(72, 72, 72)
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono_Movil, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(txtCorreo_Electronico))
                        .addGap(220, 220, 220))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_UsuarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(panel_UsuarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_UsuarioLayout.setVerticalGroup(
            panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_UsuarioLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_UsuarioLayout.createSequentialGroup()
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono_Movil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_UsuarioLayout.createSequentialGroup()
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)))
                .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCorreo_Electronico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_UsuarioLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres_Completos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrimer_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSegundo_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_UsuarioLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnMostrar_Form.setText("Ocultar Formualrio");
        btnMostrar_Form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrar_FormActionPerformed(evt);
            }
        });

        tableGrid.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Código", "Número Identificación", "Nombres", "Apellido1", "Apellido2", "Teléfono1", "Teléfono2", "Correo", "Nombre Usuario"
            }
        ));
        jScrollPane1.setViewportView(tableGrid);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscar_Todos.setText("Todos");
        btnBuscar_Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar_TodosActionPerformed(evt);
            }
        });

        jLabel15.setText("Id");

        jLabel18.setText("Nombre");

        jLabel19.setText("Numero Identidad");

        javax.swing.GroupLayout panelGridLayout = new javax.swing.GroupLayout(panelGrid);
        panelGrid.setLayout(panelGridLayout);
        panelGridLayout.setHorizontalGroup(
            panelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGridLayout.createSequentialGroup()
                .addGroup(panelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGridLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGridLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(panelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscar_Identificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(75, 75, 75)
                        .addGroup(panelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscar_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(95, 95, 95)
                        .addGroup(panelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscar_numeroDocumento)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar_Todos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGridLayout.setVerticalGroup(
            panelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGridLayout.createSequentialGroup()
                .addGroup(panelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGridLayout.createSequentialGroup()
                        .addGroup(panelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(panelGridLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar_numeroDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelGridLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar_Todos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnTipo_Documento.setBackground(new java.awt.Color(153, 153, 153));
        btnTipo_Documento.setText("Tipo Documento");
        btnTipo_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipo_DocumentoActionPerformed(evt);
            }
        });

        btnEstado.setBackground(new java.awt.Color(153, 153, 153));
        btnEstado.setText("Estado");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        btnPermisos.setBackground(new java.awt.Color(153, 153, 153));
        btnPermisos.setText("Perfiles - Permisos");
        btnPermisos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPermisosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMostrar_Form, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTipo_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPermisos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrar_Form)
                    .addComponent(btnTipo_Documento)
                    .addComponent(btnEstado)
                    .addComponent(btnPermisos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelGrid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefono1ActionPerformed

    private void txtNombres_CompletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombres_CompletosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombres_CompletosActionPerformed

    private void txtPrimer_ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimer_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimer_ApellidoActionPerformed

    private void txtNombre_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_UsuarioActionPerformed

    private void cbxPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPerfilActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxPerfilActionPerformed

    private void txtTelefono2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefono2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefono2ActionPerformed

    private void btnOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcionActionPerformed
        String g = btnOpcion.getText();
        switch (g) {
            case "Eliminar":
                this.eliminar();
                break;
        }
        btnPorDefecto();
        limpiarCampos();
    }//GEN-LAST:event_btnOpcionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiarCampos();
        btnPorDefecto();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNumero_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumero_DocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumero_DocumentoActionPerformed

    private void btnMostrar_FormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrar_FormActionPerformed
        panel_Usuario.setVisible(!panel_Usuario.isVisible());
        if (panel_Usuario.isVisible() == true) {
            btnMostrar_Form.setText("Ocultar Formulario");
        } else {
            btnMostrar_Form.setText("Mostrar Formulario");

        }
    }//GEN-LAST:event_btnMostrar_FormActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String g = btnGuardar.getText();
        switch (g) {
            case "Guardar":
                this.guardar();
                break;
            case "Guardar Cambios":
                this.editar();
                break;
        }
        btnPorDefecto();
        limpiarCampos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnTipo_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipo_DocumentoActionPerformed
        SessionUser.isValidarSessionJFrame(new Ventanas.Tipo_Documento(this), SessionUser.isTipodocumento);
    }//GEN-LAST:event_btnTipo_DocumentoActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        SessionUser.isValidarSessionJFrame(new Ventanas.Estado(this), SessionUser.isEstado);
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void btnPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPermisosActionPerformed
        SessionUser.isValidarSessionJFrame(new Ventanas.Perfil_has_Permisos(this), SessionUser.isPerfil);
    }//GEN-LAST:event_btnPermisosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        findAll(implUsuario.buscar(txtBuscar_Identificacion.getText(), txtBuscar_Nombre.getText(), txtBuscar_numeroDocumento.getText()));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscar_TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar_TodosActionPerformed
        findAllEntities();
        txtBuscar_Identificacion.setText("");
        txtBuscar_Nombre.setText("");
        txtBuscar_numeroDocumento.setText("");
    }//GEN-LAST:event_btnBuscar_TodosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager AvancePhilaePUEntityManager;
    private javax.swing.JLabel JLabel14;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar_Todos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMostrar_Form;
    private javax.swing.JButton btnOpcion;
    private javax.swing.JButton btnPermisos;
    private javax.swing.JButton btnTipo_Documento;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbxEstado;
    private javax.swing.JComboBox cbxPerfil;
    private javax.swing.JComboBox cbxTipoDocumento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelGrid;
    private javax.swing.JPanel panel_Usuario;
    private javax.swing.JTable tableGrid;
    private javax.swing.JTextField txtBuscar_Identificacion;
    private javax.swing.JTextField txtBuscar_Nombre;
    private javax.swing.JTextField txtBuscar_numeroDocumento;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtConfirmar_Clave;
    private javax.swing.JTextField txtCorreo_Electronico;
    private javax.swing.JTextField txtNombre_Usuario;
    private javax.swing.JTextField txtNombres_Completos;
    private javax.swing.JTextField txtNumero_Documento;
    private javax.swing.JTextField txtPrimer_Apellido;
    private javax.swing.JTextField txtSegundo_Apellido;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTelefono2;
    private javax.swing.JTextField txtTelefono_Movil;
    private java.util.List<Persistencia.Entities.Usuario> usuarioList;
    private javax.persistence.Query usuarioQuery;
    // End of variables declaration//GEN-END:variables

    private void initData() {
        initTipoDocumento();
        initEstado();
        initPerfil();
    }

    public void initTipoDocumento() {
        cbxTipoDocumento.removeAllItems();
        List<TipoDocumento> listaTipoDocumento = implTipo_documento.findTipoDocumentoEntities();
        for (int i = 0; i < listaTipoDocumento.size(); i++) {
            cbxTipoDocumento.addItem(new ComboItem(listaTipoDocumento.get(i).getDescripcion(), listaTipoDocumento.get(i).getIdTipodocumento().toString()));
        }
    }

    public void initEstado() {
        cbxEstado.removeAllItems();
        List<Estado> listaEstado = implEstado.findEstadoEntities();
        for (int i = 0; i < listaEstado.size(); i++) {
            cbxEstado.addItem(new ComboItem(listaEstado.get(i).getDescripcion(), listaEstado.get(i).getIdEstado().toString()));
        }
    }

    public void initPerfil() {
        cbxPerfil.removeAllItems();
        List<Perfil> listPerfil = implPerfil.findPerfilEntities();
        for (int i = 0; i < listPerfil.size(); i++) {
            cbxPerfil.addItem(new ComboItem(listPerfil.get(i).getDescripcion(), listPerfil.get(i).getIdperfil().toString()));
        }
    }

    public void cargarDatoGrid(String codigo) {
        String numero_documento = txtNumero_Documento.getText();
        String nombres_completos = txtNombres_Completos.getText();
        String primer_apellido = txtPrimer_Apellido.getText();
        String segundo_apellido = txtSegundo_Apellido.getText();
        String telefono1 = txtTelefono1.getText();
        String telefono2 = txtTelefono2.getText();
        String telefono_movil = txtTelefono_Movil.getText();
        String correo_electronico = txtCorreo_Electronico.getText();
        String nombre_usuario = txtNombre_Usuario.getText();
        String clave = txtClave.getText();
        String confirmar_clave = txtConfirmar_Clave.getText();
        addRow(codigo, numero_documento, nombres_completos, primer_apellido, segundo_apellido, telefono1, telefono2, telefono_movil, correo_electronico, nombre_usuario);
    }

    public void addRow(String codigo, String numero_documento, String nombres_completos, String primer_apellido, String segundo_apellido, String telefono1, String telefono2, String telefono_movil, String correo_electronico, String nombre_usuario) {
        DefaultTableModel model = (DefaultTableModel) tableGrid.getModel();
        model.addRow(new Object[]{codigo, numero_documento, nombres_completos, primer_apellido, segundo_apellido, telefono1, telefono2, telefono_movil, correo_electronico, nombre_usuario});
    }

    private void limpiarCampos() {
        txtCodigo.setText("");
        txtNumero_Documento.setText("");
        txtNombres_Completos.setText("");
        txtPrimer_Apellido.setText("");
        txtSegundo_Apellido.setText("");
        txtTelefono1.setText("");
        txtTelefono2.setText("");
        txtTelefono_Movil.setText("");
        txtCorreo_Electronico.setText("");
        txtNombre_Usuario.setText("");
        txtClave.setText("");
        txtConfirmar_Clave.setText("");
    }

    private void initElement() {
        findAllEntities();
        tableGrid.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                int fila = tableGrid.rowAtPoint(e.getPoint());
                int columna = tableGrid.columnAtPoint(e.getPoint());
                if ((fila > -1) && (columna > -1)) {
                    //Faltan los Combobox
                    Usuario usuario = implUsuario.finUsuario(Integer.parseInt((getRowVector(fila)[0]).trim()));

                    selectItemCBX(cbxEstado, usuario, "Estado");
                    selectItemCBX(cbxTipoDocumento, usuario, "TipoDocumento");
                    selectItemCBX(cbxPerfil, usuario, "Perfil");

                    txtCodigo.setText(usuario.getIdUsuario().toString());
                    txtNumero_Documento.setText(usuario.getNumerodocumento());
                    txtNombres_Completos.setText(usuario.getNombres());
                    txtPrimer_Apellido.setText(usuario.getApellido1());
                    txtSegundo_Apellido.setText(usuario.getApellido2());
                    txtTelefono1.setText(String.valueOf(usuario.getTelefono1()));
                    txtTelefono2.setText(String.valueOf(usuario.getTelefono2()));
                    txtTelefono_Movil.setText(usuario.getTelefonomovil());
                    txtCorreo_Electronico.setText(usuario.getCorreo());
                    txtNombre_Usuario.setText(usuario.getNombreusuario());
                    txtClave.setText(usuario.getClave());
                    txtConfirmar_Clave.setText(usuario.getClave());

                    btnGuardar.setText("Guardar Cambios");
                    btnOpcion.setText("Eliminar");
                    panel_Usuario.setVisible(true);
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
    }

    public void selectItemCBX(JComboBox jComboBox, Usuario usuario, String action) {
        for (int i = 0; i < jComboBox.getItemCount(); i++) {
            ComboItem comboItem = (ComboItem) jComboBox.getItemAt(i);
            switch (action) {
                case "Perfil":
                    if (comboItem.getValue().equals(usuario.getIdperfil().getIdperfil().toString())) {
                        jComboBox.setSelectedIndex(i);
                    }
                    break;
                case "Estado":
                    if (comboItem.getValue().equals(usuario.getIdEstado().getIdEstado().toString())) {
                        jComboBox.setSelectedIndex(i);
                    }
                    break;
                case "TipoDocumento":
                    if (comboItem.getValue().equals(usuario.getIdTipodocumento().getIdTipodocumento().toString())) {
                        jComboBox.setSelectedIndex(i);
                    }
                    break;

            }

        }
    }

    public String[] getRowVector(int fila) {
        DefaultTableModel model = (DefaultTableModel) tableGrid.getModel();
        int col = tableGrid.getColumnCount();
        String result = "";
        for (int i = 0; i < col; i++) {
            result += (i == 0 ? "" : " - ") + model.getValueAt(fila, i).toString();
        }
        return result.split("-");
    }

    private void btnPorDefecto() {
        btnGuardar.setText("Guardar");
        btnOpcion.setText("Nuevo");
    }

    public void guardar() {
        try {
            Boolean validar = true;
            if (txtNumero_Documento.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Campo vacío, digitar número de documento");
                return;
            }
            if (txtNombres_Completos.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Campo vacío, digitar nombres");
                return;
            }
            if (txtPrimer_Apellido.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Campo vacío, digitar primer apellido");
                return;

            }
            if (txtSegundo_Apellido.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Campo vacío, digitar segundo apellido");
                return;

            }
            if (txtTelefono1.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Campo vacío, digitar número telefónico");
                return;
            }
            
           
           
            if (txtNombre_Usuario.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Campo vacío, digitar nombre de usuario");
                return;
            }
            String Clave=new String(txtClave.getPassword());
            String Confirmar_Clave=new String(txtConfirmar_Clave.getPassword());
            
            if (Clave.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Campo vacío, digitar clave");
                return;
            }
            if (Confirmar_Clave.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Campo vacío, digitar confirmación clave");
                return;
            } 
            
            if (!Clave.equals(Confirmar_Clave)) {
                JOptionPane.showMessageDialog(rootPane, "La contraseña no coincide");
                validar = false;
            }
            if (validar) {
                Persistencia.Entities.Usuario usuario = new Persistencia.Entities.Usuario();
                ComboItem valueTipoDocumento = (ComboItem) cbxTipoDocumento.getSelectedItem();
                usuario.setIdTipodocumento(implTipo_documento.findTipoDocumentoById(Integer.parseInt(valueTipoDocumento.getValue())));
                usuario.setNumerodocumento(txtNumero_Documento.getText());
                usuario.setNombres(txtNombres_Completos.getText());
                usuario.setApellido1(txtPrimer_Apellido.getText());
                usuario.setApellido2(txtSegundo_Apellido.getText());
                usuario.setTelefono1(Integer.parseInt(txtTelefono1.getText()));
                usuario.setTelefono2(Integer.parseInt(txtTelefono2.getText()));
                usuario.setTelefonomovil(txtTelefono_Movil.getText());
                usuario.setCorreo(txtCorreo_Electronico.getText());
                usuario.setClave(txtClave.getText());
                ComboItem valueEstado = (ComboItem) cbxEstado.getSelectedItem();
                usuario.setIdEstado(implEstado.finEstadoById(Integer.parseInt(valueEstado.getValue())));
                usuario.setNombreusuario(txtNombre_Usuario.getText());
                ComboItem valuePerfil = (ComboItem) cbxPerfil.getSelectedItem();
                usuario.setIdperfil(implPerfil.findPerfilById(Integer.parseInt(valuePerfil.getValue())));

                if (implUsuario.createUsuario(usuario) != null) {
                    JOptionPane.showMessageDialog(this, "Usuario creado");
                    cargarDatoGrid(usuario.getIdUsuario().toString());
                    panel_Usuario.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Error al crear el Usuario");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    private void editar() {
        try {
            Boolean validar = true;
            if (txtNumero_Documento.getText().equals("")) {
                validar = false;
            }
            if (txtNombres_Completos.getText().equals("")) {
                validar = false;
            }
            if (txtPrimer_Apellido.getText().equals("")) {
                validar = false;
            }
            if (txtSegundo_Apellido.getText().equals("")) {
                validar = false;
            }
            if (txtTelefono1.getText().equals("")) {
                validar = false;
            }
            if (txtTelefono2.getText().equals("")) {
                validar = false;
            }
            if (txtTelefono_Movil.getText().equals("")) {
                validar = false;
            }
            if (txtCorreo_Electronico.getText().equals("")) {
                validar = false;
            }
            if (txtNombre_Usuario.getText().equals("")) {
                validar = false;
            }
            if (!txtClave.getText().equals(txtConfirmar_Clave.getText())) {
                JOptionPane.showMessageDialog(rootPane, "La contraseña no coincide");
                validar = false;
            }
            if (validar) {
                Persistencia.Entities.Usuario usuario = implUsuario.finUsuario(Integer.parseInt(txtCodigo.getText().trim()));

                ComboItem valueTipoDocumento = (ComboItem) cbxTipoDocumento.getSelectedItem();
                usuario.setIdTipodocumento(implTipo_documento.findTipoDocumentoById(Integer.parseInt(valueTipoDocumento.getValue())));

                usuario.setNumerodocumento(txtNumero_Documento.getText());
                usuario.setNombres(txtNombres_Completos.getText());
                usuario.setApellido1(txtPrimer_Apellido.getText());
                usuario.setApellido2(txtSegundo_Apellido.getText());
                usuario.setTelefono1(Integer.parseInt(txtTelefono1.getText()));
                usuario.setTelefono2(Integer.parseInt(txtTelefono2.getText()));
                usuario.setTelefonomovil(txtTelefono_Movil.getText());
                usuario.setCorreo(txtCorreo_Electronico.getText());
                usuario.setClave(txtClave.getText());
                ComboItem valueEstado = (ComboItem) cbxEstado.getSelectedItem();
                usuario.setIdEstado(implEstado.finEstadoById(Integer.parseInt(valueEstado.getValue())));

                usuario.setNombreusuario(txtNombre_Usuario.getText());

                ComboItem valuePerfil = (ComboItem) cbxPerfil.getSelectedItem();
                usuario.setIdperfil(implPerfil.findPerfilById(Integer.parseInt(valuePerfil.getValue())));

                if (implUsuario.editarUsuario(usuario) != null) {
                    JOptionPane.showMessageDialog(this, "Usuario Editado");
                    clear_Table();
                    findAllEntities();
                    panel_Usuario.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Error al Editar el Usuario");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    private void eliminar() {
        try {
            Boolean validar = true;
            if (txtCodigo.getText().equals("")) {
                validar = false;
            }
            if (validar) {
                Persistencia.Entities.Usuario usuario = implUsuario.finUsuario(Integer.parseInt(txtCodigo.getText().trim()));
                if (implUsuario.elimiarUsuario(usuario) == null) {
                    JOptionPane.showMessageDialog(this, "Usuario Eliminado");
                    clear_Table();
                    findAllEntities();
                    panel_Usuario.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Error al Eliminar el Usuario");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error");
            e.printStackTrace();
        }
    }

    private void findAllEntities() {
        clear_Table();
        List<Persistencia.Entities.Usuario> list = implUsuario.finUsuariosEntities();
        for (int i = 0; i < list.size(); i++) {
            addRow(list.get(i).getIdUsuario().toString(),
                    list.get(i).getNumerodocumento(),
                    list.get(i).getNombres(),
                    list.get(i).getApellido1(),
                    list.get(i).getApellido2(),
                    String.valueOf((list.get(i).getTelefono1())),
                    String.valueOf((list.get(i).getTelefono2())),
                    list.get(i).getTelefonomovil(),
                    list.get(i).getCorreo(),
                    list.get(i).getNombreusuario());
        }
    }

    private void findAll(List<Usuario> list) {
        clear_Table();
        for (int i = 0; i < list.size(); i++) {
            addRow(list.get(i).getIdUsuario().toString(),
                    list.get(i).getNumerodocumento(),
                    list.get(i).getNombres(),
                    list.get(i).getApellido1(),
                    list.get(i).getApellido2(),
                    String.valueOf((list.get(i).getTelefono1())),
                    String.valueOf((list.get(i).getTelefono2())),
                    list.get(i).getTelefonomovil(),
                    list.get(i).getCorreo(),
                    list.get(i).getNombreusuario());
        }
    }

    private void clear_Table() {
        DefaultTableModel modelo = (DefaultTableModel) tableGrid.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    private boolean isValidarSession() {
        Usuario usuario = SessionUser.getUsuario();
        Boolean res = false;
        if (usuario != null) {
            List<Persistencia.Entities.Permisos> listP = usuario.getIdperfil().getPermisosList();
            for (int i = 0; i < listP.size(); i++) {
                if (listP.get(i).getIdPermisos() == SessionUser.isUsuarios) {
                    res = true;
                }
            }
        }
        return res;
    }
    public void permisos(){
        
        txtCodigo.setEditable(false);
        cbxTipoDocumento.setEnabled(false);
        txtNumero_Documento.setEditable(false);
        txtNombres_Completos.setEditable(false);
        txtPrimer_Apellido.setEditable(false);
        txtSegundo_Apellido.setEditable(false);
        txtTelefono1.setEditable(false);
        txtTelefono2.setEditable(false);
        txtTelefono_Movil.setEditable(false);
        txtCorreo_Electronico.setEditable(false);
        cbxEstado.setEnabled(false);
        txtNombre_Usuario.setEditable(false);
        txtClave.setEditable(false);
        txtConfirmar_Clave.setEditable(false);
        cbxPerfil.setEnabled(false);        
        btnGuardar.setEnabled(false);   
        btnOpcion.setEnabled(false);   
        btnCancelar.setEnabled(false);
    }

}
